### ISSUE TITLE
Cannot create multiple chess boards using v-for

### ISSUE THREAD

**Issue by jeanayee** [vitogit/vue-chessboard#7] opened 2019-08-04 22:06 UTC
```
<div v-for="fen in fens">
   <chessboard :fen="fen" />
</div>
```
This shows the default starting chessboard setups instead of the associated fens, where `fens = ["rnbqkbnr/ppp1pppp/3p4/8/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq -", "r2kr1n1/pp3pbp/6p1/K4b2/2N1p3/1P1qQ2P/P1N2PP1/3R1Rn1 w KQkq -"]`

**Comment by vitogit** [comment] 2020-03-14 23:56
Hi @jeanayee I can't reproduce that issue. You can check a working example here 
(Multiple Chessboards with different fens.)
https://github.com/vitogit/vue-chessboard-examples#multiple-chessboards-with-different-fens

Source code: https://github.com/vitogit/vue-chessboard-examples/blob/master/src/App.vue#L29

I will close the issue, but if you still have the same problem let me know and I will reopen

**Closed by vitogit** 2020-03-14 23:56 UTC
